### ISSUE TITLE
Speech doesn't work

### ISSUE THREAD

**Issue by gamer0mega** [DuncteBot/skybot-lavalink-plugin#16] opened 2023-02-16 20:16 UTC
## Description
Whenever I try to load a speak:... track, in return I get "NO_MATCHES". The tts source is enabled in the configuration and it is logged to be registered.

## Version info
**Client used:** My own

Output of `java -version`:
```
openjdk version "18.0.2-ea" 2022-07-19
OpenJDK Runtime Environment (build 18.0.2-ea+9-Ubuntu-2)
OpenJDK 64-Bit Server VM (build 18.0.2-ea+9-Ubuntu-2, mixed mode, sharing)
```

## Logs

```
2023-02-16 23:09:50.022  INFO 383992 --- [           main] lavalink.server.bootstrap.PluginManager  : Loaded skybot-lavalink-plugin-1.4.1.jar (3 classes)
2023-02-16 23:09:50.120  INFO 383992 --- [           main] lavalink.server.Launcher                 : Started Launcher in 1.073 seconds (JVM running for 1.507)
2023-02-16 23:09:50.122  INFO 383992 --- [           main] lavalink.server.Launcher                 : You can safely ignore the big red warning about illegal reflection. See https://github.com/freyacodes/Lavalink/issues/295
2023-02-16 23:09:50.174  INFO 383992 --- [           main] lavalink.server.Launcher                 : 

	Version:        3.7.4
	Build time:     02.02.2023 18:34:07 UTC
	Branch          HEAD
	Commit:         8ebaba1
	Commit time:    02.02.2023 18:32:05 UTC
	JVM:            18.0.2-ea
	Lavaplayer      1.3.99.2-original

2023-02-16 23:09:50.180  INFO 383992 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2023-02-16 23:09:50.831  WARN 383992 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2023-02-16 23:09:50.864  INFO 383992 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2023-02-16 23:09:50.864  INFO 383992 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 680 ms
2023-02-16 23:09:50.946  WARN 383992 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2023-02-16 23:09:51.107  INFO 383992 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2023-02-16 23:09:51.121  INFO 383992 --- [           main] c.d.lavalinkplugin.DuncteBotInjector     : Registering getyarn audio source manager
2023-02-16 23:09:51.123  INFO 383992 --- [           main] c.d.lavalinkplugin.DuncteBotInjector     : Registering clypit audio source manager
2023-02-16 23:09:51.124  INFO 383992 --- [           main] c.d.lavalinkplugin.DuncteBotInjector     : Registering text to speech audio source manager with language en-AU
2023-02-16 23:09:51.125  INFO 383992 --- [           main] c.d.lavalinkplugin.DuncteBotInjector     : Registering PornHub audio source manager
2023-02-16 23:09:51.126  INFO 383992 --- [           main] c.d.lavalinkplugin.DuncteBotInjector     : Registering reddit audio source manager
2023-02-16 23:09:51.127  INFO 383992 --- [           main] c.d.lavalinkplugin.DuncteBotInjector     : Registering OC Remix audio source manager
2023-02-16 23:09:51.131  INFO 383992 --- [           main] c.d.lavalinkplugin.DuncteBotInjector     : Registering TikTok audio source manager
2023-02-16 23:09:51.132  INFO 383992 --- [           main] c.d.lavalinkplugin.DuncteBotInjector     : Registering Mixcloud audio source manager
2023-02-16 23:09:51.132  INFO 383992 --- [           main] c.d.lavalinkplugin.DuncteBotInjector     : Registering Soundgasm audio source manager
2023-02-16 23:09:51.242  INFO 383992 --- [           main] lavalink.server.config.KoeConfiguration  : OS: LINUX, Arch: X86_64
...
-16 23:09:51.855  INFO 383992 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2023-02-16 23:09:51.867  INFO 383992 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:39772
2023-02-16 23:09:51.867  INFO 383992 --- [  XNIO-1 task-2] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:39766
2023-02-16 23:09:52.036  INFO 383992 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from BruhBot Canary
2023-02-16 23:09:52.037  INFO 383992 --- [  XNIO-1 task-2] lavalink.server.io.SocketServer          : Connection successfully established from BruhBot Canary
2023-02-16 23:10:25.845  INFO 383992 --- [  XNIO-1 task-3] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "speak:testing"
2023-02-16 23:10:25.847  INFO 383992 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : No matches found
```

**Comment by duncte123** [comment] 2023-02-16 20:57
What version of the plugin are you using?
I cannot reproduce this bug, please share some more info on how you are loading the track

**Comment by gamer0mega** [comment] 2023-02-17 08:34
> What version of the plugin are you using?
I cannot reproduce this bug, please share some more info on how you are loading the track

You can see the version of the plugin in the logs (1.4.1). I load tracks using the /v3/loadtracks?identifier=... lavalink endpoint.

**Comment by duncte123** [comment] 2023-05-23 07:06
Can you try it again with version `1.4.2`?

**Comment by duncte123** [comment] 2023-07-07 16:36
Closing this issue as it works for me, feel free to re-open if it's still broken.

**Closed as completed by duncte123** 2023-07-07 16:36 UTC
